// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.fundatiacomunitarabucuresti.volunteer.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ro.fundatiacomunitarabucuresti.volunteer.domain.City;
import ro.fundatiacomunitarabucuresti.volunteer.domain.CityDataOnDemand;
import ro.fundatiacomunitarabucuresti.volunteer.services.CityService;

privileged aspect CityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CityDataOnDemand: @Component;
    
    private Random CityDataOnDemand.rnd = new SecureRandom();
    
    private List<City> CityDataOnDemand.data;
    
    @Autowired
    CityService CityDataOnDemand.cityService;
    
    public City CityDataOnDemand.getNewTransientCity(int index) {
        City obj = new City();
        setName(obj, index);
        return obj;
    }
    
    public void CityDataOnDemand.setName(City obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public City CityDataOnDemand.getSpecificCity(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        City obj = data.get(index);
        Long id = obj.getId();
        return cityService.findCity(id);
    }
    
    public City CityDataOnDemand.getRandomCity() {
        init();
        City obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return cityService.findCity(id);
    }
    
    public boolean CityDataOnDemand.modifyCity(City obj) {
        return false;
    }
    
    public void CityDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = cityService.findCityEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'City' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<City>();
        for (int i = 0; i < 10; i++) {
            City obj = getNewTransientCity(i);
            try {
                cityService.saveCity(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
