// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.fundatiacomunitarabucuresti.volunteer.domain;

import ro.fundatiacomunitarabucuresti.volunteer.domain.Skill;

privileged aspect Skill_Roo_JavaBean {
    
    public String Skill.getName() {
        return this.name;
    }
    
    public void Skill.setName(String name) {
        this.name = name;
    }
    
}
