// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ro.fundatiacomunitarabucuresti.volunteer.domain;

import org.springframework.beans.factory.annotation.Configurable;
import ro.fundatiacomunitarabucuresti.volunteer.domain.Tag;

privileged aspect Tag_Roo_Configurable {
    
    declare @type: Tag: @Configurable;
    
}
